Linechart component
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P2-WildWeather pull request #19
Opened 2024-07-10 14:22 UTC by monica-tech75

2024-07-10 15:06 UTC, CyrThoDev reviewed
Voir mes commentaires

2024-07-10 15:06 UTC, CyrThoDev commented on client/src/components/LineCharts.jsx
> +  console.info(forecast);
enlever le console.info

2024-07-10 15:06 UTC, CyrThoDev commented on client/src/components/LineCharts.jsx
> +  const data = [
mettre la data dans un fichier data séparé pour plus de lisibilité

2024-07-10 15:06 UTC, CyrThoDev requested changes
Voi mes commentaires

2024-07-11 08:16 UTC, CyrThoDev approved these changes
ok

2024-07-11 08:17 UTC, RossAlex0 approved these changes
Ok

2024-07-11 08:17 UTC, RossAlex0 commented on client/src/components/HomeCarousel.jsx
> +      <LineCharts forecast={forecastWeather} />
Le composants va dans la page Home.jsx !

2024-07-11 08:17 UTC, RossAlex0 commented on client/src/pages/Home.jsx
> -      setInputCity('')
?

2024-07-11 08:17 UTC, merged