Create component Settings
WildCodeSchool-2024-02/JS-RemoteFR-CodeOfWar-P2-WildWeather pull request #24
Opened 2024-07-12 10:10 UTC by RossAlex0

2024-07-12 14:51 UTC, CyrThoDev requested changes
Quelques petites lignes à enlever

2024-07-12 14:51 UTC, CyrThoDev commented on client/src/components/Settings.jsx
> +  // const navigate = useNavigate();
A enlever ^^

2024-07-12 14:51 UTC, CyrThoDev commented on client/src/components/Settings.jsx
> +    // navigate(`/${path}`)
idem enlever le commentaire

2024-07-12 14:51 UTC, CyrThoDev commented on client/src/components/Settings.jsx
> +    console.info(`/${navigTo}`);
enlever le console.info

2024-07-12 15:35 UTC, CyrThoDev approved these changes
ok c'est bon!

2024-07-15 07:06 UTC, kpeset approved these changes
Approuvé !

2024-07-15 07:06 UTC, merged